<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_acf_hero-image-fields',
	'title' => 'Hero Image Fields',
	'fields' => array (
		array (
			'key' => 'field_58cbf49a1d070',
			'label' => 'Content Source',
			'name' => 'content_source',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'static' => 'Static',
				'latestpost' => 'Latest Posts',
				'specificpost' => 'Specific Post',
				'search' => 'Site Search',
				'remote' => 'Remote WP Content',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'static',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_58cbf5ca1d071',
			'label' => 'Post Categories to Show',
			'name' => 'hero_post_categories',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'latestpost',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_58cbf61b1d072',
			'label' => 'Post Offset',
			'name' => 'hero_post_offset',
			'type' => 'number',
			'instructions' => 'Example: 0 Shows the latest post, 1 Shows the second to latest post, 2 Shows the third...',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'latestpost',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58cbf6961d073',
			'label' => 'Show Specific Post or Page',
			'name' => 'show_specific_post',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'specificpost',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
				1 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_554146e0cd9b4',
			'label' => 'Sub Heading Text',
			'name' => 'sub_heading_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'static',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_576961e2c6ddf',
			'label' => 'Hide Slide Text',
			'name' => 'hide_slide_text',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'static',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'hide' => 'Hide Text',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'allow_custom' => 0,
			'save_custom' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_554146f2cd9b5',
			'label' => 'Link To',
			'name' => 'link_to',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'static',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'Do not link',
				'pageorpost' => 'Link to a Page or Post',
				'externalurl' => 'Specify a URL',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'none',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5541473ccd9b6',
			'label' => 'Link to a Page or Post',
			'name' => 'link_to_a_page_or_post',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_554146f2cd9b5',
						'operator' => '==',
						'value' => 'pageorpost',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
				1 => 'page',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'taxonomy' => array (
			),
			'allow_archives' => 1,
		),
		array (
			'key' => 'field_554147f9cd9b7',
			'label' => 'Specify a URL',
			'name' => 'specify_a_url',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_554146f2cd9b5',
						'operator' => '==',
						'value' => 'externalurl',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'www.wisc.edu',
			'prepend' => 'http://',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55414630cd9b2',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'static',
					),
				),
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'search',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55f87f434dc2e',
			'label' => 'Hero Video',
			'name' => 'hero_video',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'static',
					),
				),
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'search',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5978f58469076',
			'label' => 'Remote URL',
			'name' => 'remote_url',
			'type' => 'url',
			'instructions' => 'Enter the primary domain for the site. For example: https://news.cals.wisc.edu',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'remote',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5978f67169079',
			'label' => 'Remote Image Fallback',
			'name' => 'remote_image_fallback',
			'type' => 'image',
			'instructions' => 'Select an image to use when no remote image is found.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'remote',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5978f5c569077',
			'label' => 'Remote Content Offset',
			'name' => 'remote_content_offset',
			'type' => 'number',
			'instructions' => '0 is the default which shows the latest post. 1 would show the second to latest post.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'remote',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5978f61369078',
			'label' => 'Remote Category ID',
			'name' => 'remote_category_id',
			'type' => 'number',
			'instructions' => 'Enter the category ID to retrieve.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58cbf49a1d070',
						'operator' => '==',
						'value' => 'remote',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57696007ab6c2',
			'label' => 'Hero Image Vertical Alignment',
			'name' => 'hero_image_vertical_alignment',
			'type' => 'radio',
			'instructions' => 'To accommodate various browser and device sizes the images will auto resize and crop when needed. Would you like this image to auto resize itself from the top, center, or bottom of the image?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'top' => 'Top',
				'center' => 'Centered',
				'bottom' => 'Bottom',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'center',
			'layout' => 'vertical',
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_576960b2ab6c3',
			'label' => 'Disable Image Filter?',
			'name' => 'hero_image_filter',
			'type' => 'checkbox',
			'instructions' => 'In order to provide contrast to any text on top of the image this theme places a subtle darkening filter on the image.	If you would like to disable this, check this box.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'allow_custom' => 0,
			'save_custom' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_57696121ab6c4',
			'label' => 'Disable Blur Filter?',
			'name' => 'disable_blur_filter',
			'type' => 'checkbox',
			'instructions' => 'In order to make navigation text readable in the event of a detailed image this theme will blur the top portion of the image.	If you would like to disable this, check this box.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
			),
			'default_value' => array (
				0 => 'no',
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'allow_custom' => 0,
			'save_custom' => 0,
			'return_format' => 'value',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'headerslides',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;